### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by ThatonePanMan** [HolographicWings/LethalSDK-Unity-Project#79]
Since there's no documentation yet for anything, some parts still confuse me

1) How does the Enemy Spawn Chance Throughout Day work? I get it's a curve and it increases as the day progresses, but what do the values mean? Is 1 on the horizontal axis the end of the day or is it 1 hour into a day?

2) Same goes for Outside Enemy Spawn Chance Through Day? Where on the graph is 3:00 pm like normal moons?

3) How to the spawn graphs for Turrets and Landmines work? Is it distance from the entrance?

4) How do Flashlight scraps work? What do I need to put in stuff like Flashlight Bulb and Flashlight Bulb Glow? What about Flashlight Mesh? What does Flashlight Type ID mean? What is Flashlight Interference Level for?

**Comment by ThatonePanMan** [comment]
Also, tweaking the sky and fog global volume doesn't seem to change anything
the sky is grey instead of a custom cubemap I placed in and clouds are still there despite being disabled on volume

**Comment by HolographicWings** [comment]
> Since there's no documentation yet for anything, some parts still confuse me
> 
> 1. How does the Enemy Spawn Chance Throughout Day work? I get it's a curve and it increases as the day progresses, but what do the values mean? Is 1 on the horizontal axis the end of the day or is it 1 hour into a day?
> 2. Same goes for Outside Enemy Spawn Chance Through Day? Where on the graph is 3:00 pm like normal moons?
> 3. How to the spawn graphs for Turrets and Landmines work? Is it distance from the entrance?
> 4. How do Flashlight scraps work? What do I need to put in stuff like Flashlight Bulb and Flashlight Bulb Glow? What about Flashlight Mesh? What does Flashlight Type ID mean? What is Flashlight Interference Level for?

about the curves i fear i can't help you a much, the SDK simply port the curves to the vanilla classes, i myself barely understand how they act
the day is counted on a value from 0 to 1

same about flashlight, it's just porting fields
the bulbs are the light components of the flashlight, they are toggled
in the vanilla flashlights, the mesh is be the mesh renderer of the flashlight itself but i don't know if theres any point to define it
and i don't have any idea about what is the ID
Interference may be flickering

for the volume, it's because you try to edit the volume that is in the Lethal Expansion module
so, in the LethalExpansion.lem file, so ofc you can't modify it
you must put your own volume profile in your module folder to customize it

**Comment by ThatonePanMan** [comment]
ok, well at least knowing the day is on a value of 0 to 1 helps a lot

I figured that editing the volume in the scene would work, so do I have to make a prefab of the volume from the scene to my mod's folder or do I have to copy the files from the lethalexpansion folder to my mod's folder?

**Comment by HolographicWings** [comment]
Not especially a prefab
Use a prefab from the LethalExpansion module makes it auto update in your map
If you use your own volume you don't need a prefab
Except if you use another module as dependency and this prefab is in this dependency

**Comment by ThatonePanMan** [comment]
Solved it by just grabbing the Volume Profile file that was attached to the gameobject and moving it from the LethalExpansion folder to my mod's folder

Also, for future reference for anyone who has a similar confusion with how the enemy spawning curves correlate to time, here's a handy little bit of math I did to figure out what horizontal value correlates to each in game hour
![image](https://github.com/HolographicWings/LethalSDK-Unity-Project/assets/157259292/777202b5-60ae-4fa7-ba0f-741cbb9b9d41)
